// Generated by tools/bdf_to_c.py from assets/fonts/*.bdf. DO NOT EDIT.
#ifndef SPIKE_FONT_DATA_H_
#define SPIKE_FONT_DATA_H_

#include <cstdint>

namespace spike {
namespace font_data {

// Terminus (SIL OFL 1.1). 96 glyphs: ASCII 0x20..0x7E, then U+00B7
// (middle dot) at index 95. Rows are bit-packed, MSB = leftmost pixel
// (left-aligned): glyph bit x lives at bit (bytes_per_row*8 - 1 - x).
inline constexpr int kFirst = 0x20;
inline constexpr int kGlyphCount = 96;

// TerU20n: 10x20, 2 bytes/row, baseline 16.
inline constexpr int kTerU20nW = 10;
inline constexpr int kTerU20nH = 20;
inline constexpr int kTerU20nBase = 16;
extern const std::uint8_t kTerU20nBits[];

// TerU14n: 8x14, 1 bytes/row, baseline 12.
inline constexpr int kTerU14nW = 8;
inline constexpr int kTerU14nH = 14;
inline constexpr int kTerU14nBase = 12;
extern const std::uint8_t kTerU14nBits[];

}  // namespace font_data
}  // namespace spike

#endif  // SPIKE_FONT_DATA_H_
