#!/usr/bin/env python3
"""BDF -> C emitter for the spike renderer's 1-bpp glyph atlases.

Reads Terminus BDF files (assets/fonts/ter-u20n.bdf, ter-u14n.bdf) and emits
spike/font_data.h with one const uint8_t array per atlas plus cell metadata.
Rows are bit-packed, MSB = leftmost pixel (left-aligned): glyph bit x lives at
bit (bytes_per_row*8 - 1 - x).

--check <html> decodes the glyph data embedded in the Nostromo mockup
(ui/mockup/nostromo_signal-flow.html) and asserts the emitted atlas is
bit-identical. Exits 0 on match, 1 on mismatch.
"""

import argparse
import base64
import re
import sys
from pathlib import Path

FIRST = 0x20  # printable ASCII range
LAST = 0x7E
EXTRA = 0xB7  # middle dot (U+00B7), appended after the ASCII block
GLYPH_COUNT = (LAST - FIRST + 1) + 1

REPO = Path(__file__).resolve().parent.parent
FONT_DIR = REPO / "assets" / "fonts"
OUT_PATH = REPO / "spike" / "font_data.h"
MOCKUP = REPO / "ui" / "mockup" / "nostromo_signal-flow.html"

# (bdf filename, C identifier)
ATLASES = [
    ("ter-u20n.bdf", "TerU20n"),
    ("ter-u14n.bdf", "TerU14n"),
]


def glyph_index(codepoint):
    """Return the atlas index for a codepoint, or None if not included."""
    if FIRST <= codepoint <= LAST:
        return codepoint - FIRST
    if codepoint == EXTRA:
        return GLYPH_COUNT - 1
    return None


def parse_bdf(path):
    """Return (fontbox, glyphs, glyph_bbx) where glyphs maps encoding ->
    bitmap bytes and glyph_bbx maps encoding -> (w, h, xoff, yoff)."""
    fontbox = None
    glyphs = {}
    glyph_bbx = {}
    encoding = None
    bbx = None
    bitmap_rows = []
    in_bitmap = False
    with open(path, encoding="ascii") as f:
        for raw in f:
            line = raw.rstrip("\n")
            if line.startswith("FONTBOUNDINGBOX"):
                _, w, h, xoff, yoff = line.split()
                fontbox = (int(w), int(h), int(xoff), int(yoff))
            elif line.startswith("ENCODING"):
                encoding = int(line.split()[1])
                bitmap_rows = []
                bbx = None
            elif line.startswith("BBX"):
                _, w, h, xoff, yoff = line.split()
                bbx = (int(w), int(h), int(xoff), int(yoff))
            elif line == "BITMAP":
                in_bitmap = True
            elif line == "ENDCHAR":
                if in_bitmap and encoding is not None:
                    glyphs[encoding] = b"".join(
                        bytes.fromhex(r) for r in bitmap_rows
                    )
                    glyph_bbx[encoding] = bbx
                in_bitmap = False
                encoding = None
                bbx = None
            elif in_bitmap:
                bitmap_rows.append(line.strip())
    return fontbox, glyphs, glyph_bbx


def build_atlas(fontbox, glyphs, glyph_bbx):
    """Return (w, h, base, bpr, atlas_bytes)."""
    w, h, xoff, yoff = fontbox
    bpr = (w + 7) // 8
    base = h + yoff  # baseline offset from the top of the cell
    out = bytearray()
    for codepoint in list(range(FIRST, LAST + 1)) + [EXTRA]:
        bbx = glyph_bbx.get(codepoint)
        if bbx != fontbox:
            raise ValueError(
                f"glyph U+{codepoint:04X}: BBX {bbx} does not fill the font "
                f"cell {fontbox}; this converter assumes fixed-size cells"
            )
        data = glyphs[codepoint]
        expected = h * bpr
        if len(data) != expected:
            raise ValueError(
                f"glyph U+{codepoint:04X}: {len(data)} bytes, expected {expected}"
            )
        out += data
    return w, h, base, bpr, bytes(out)


def c_array(name, data, bpr, bytes_per_line=16):
    lines = [f"static const std::uint8_t {name}[] = {{"]
    for i in range(0, len(data), bytes_per_line):
        chunk = data[i : i + bytes_per_line]
        hexes = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"  {hexes},")
    lines.append("};")
    return "\n".join(lines)


def emit_header(atlas_meta):
    parts = [
        "// Generated by tools/bdf_to_c.py from assets/fonts/*.bdf. DO NOT EDIT.",
        "#ifndef SPIKE_FONT_DATA_H_",
        "#define SPIKE_FONT_DATA_H_",
        "",
        "#include <cstdint>",
        "",
        "namespace spike {",
        "namespace font_data {",
        "",
        "// Terminus (SIL OFL 1.1). 96 glyphs: ASCII 0x20..0x7E, then U+00B7",
        "// (middle dot) at index 95. Rows are bit-packed, MSB = leftmost pixel",
        "// (left-aligned): glyph bit x lives at bit (bytes_per_row*8 - 1 - x).",
        f"inline constexpr int kFirst = 0x{FIRST:02X};",
        f"inline constexpr int kGlyphCount = {GLYPH_COUNT};",
        "",
    ]
    for (name, w, h, base, bpr, data) in atlas_meta:
        parts.append(
            f"// {name}: {w}x{h}, {bpr} bytes/row, baseline {base}."
        )
        parts.append(f"inline constexpr int k{name}W = {w};")
        parts.append(f"inline constexpr int k{name}H = {h};")
        parts.append(f"inline constexpr int k{name}Base = {base};")
        parts.append(c_array(f"k{name}Bits", data, bpr))
        parts.append("")
    parts += [
        "}  // namespace font_data",
        "}  // namespace spike",
        "",
        "#endif  // SPIKE_FONT_DATA_H_",
        "",
    ]
    return "\n".join(parts)


def atlas_metadata():
    meta = []
    for bdf_name, ident in ATLASES:
        fontbox, glyphs, glyph_bbx = parse_bdf(FONT_DIR / bdf_name)
        w, h, base, bpr, data = build_atlas(fontbox, glyphs, glyph_bbx)
        meta.append((ident, w, h, base, bpr, data))
    return meta


def mockup_glyphs(html_path):
    """Extract and decode the mockup's A20/A14 atlas bytes."""
    text = Path(html_path).read_text(encoding="utf-8")
    out = {}
    for name, bpr in (("A20", 2), ("A14", 1)):
        m = re.search(rf"{name}=\{{[^}}]*data:\"([^\"]*)\"", text)
        if not m:
            raise ValueError(f"mockup: no {name} atlas found in {html_path}")
        out[name] = base64.b64decode(m.group(1))
    return out


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", metavar="HTML",
                    help="verify the emitted atlas against a mockup's glyph data")
    ap.add_argument("--out", metavar="PATH", default=str(OUT_PATH),
                    help=f"output header path (default {OUT_PATH})")
    args = ap.parse_args(argv)

    meta = atlas_metadata()

    if args.check:
        mock = mockup_glyphs(args.check)
        expected = {
            "A20": meta[0][5],
            "A14": meta[1][5],
        }
        ok = True
        for name in ("A20", "A14"):
            if mock[name] != expected[name]:
                ok = False
                a, b = mock[name], expected[name]
                print(f"{name}: mockup {len(a)} bytes, emitted {len(b)} bytes",
                      file=sys.stderr)
                for i in range(min(len(a), len(b))):
                    if a[i] != b[i]:
                        _, w, h, _, bpr, _ = meta[0] if name == "A20" else meta[1]
                        gi, off = divmod(i, h * bpr)
                        print(f"  first diff at byte {i} (glyph {gi}, row {off // bpr}): "
                              f"mockup 0x{a[i]:02X} vs emitted 0x{b[i]:02X}",
                              file=sys.stderr)
                        break
        if ok:
            print(f"OK: emitted atlas is bit-identical to the mockup's A20/A14 "
                  f"glyph data ({len(expected['A20'])}+{len(expected['A14'])} bytes)")
            return 0
        print("MISMATCH: emitted atlas differs from the mockup", file=sys.stderr)
        return 1

    header = emit_header(meta)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(header, encoding="ascii")
    sizes = ", ".join(f"{name}={len(data)}B" for name, *_ , data in meta)
    print(f"wrote {out} ({sizes})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
